name: C CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jidicula/clang-format-action@v1
        with:
          check_only: true
          paths: |
            c_src/
            include/
          style: file
