name: C CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '13'
          check-path: 'c_src'
          exclude-regex: '(lz4|lz4hc|lz4frame|xxhash).(c|h)'
          fallback-style: 'LLVM'
